# Generated by Django 5.0.7 on 2024-08-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('askingPrice', models.IntegerField(default=0)),
                ('numberBeds', models.IntegerField(default=0)),
                ('numberBaths', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
