# Generated by Django 5.0.7 on 2024-08-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
