# Generated by Django 5.0.7 on 2024-08-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.URLField(default='', max_length=350),
        ),
    ]
