# Generated by Django 5.0.7 on 2024-08-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_property_image_propertyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
