# Generated by Django 5.0.7 on 2024-08-22 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_propertyimage_options_propertyimage_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={},
        ),
    ]
