# Generated by Django 5.0.7 on 2024-08-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
