# Generated by Django 5.0.7 on 2024-08-22 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_propertyimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
