# Generated by Django 5.0.7 on 2024-08-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='string_array',
            field=models.JSONField(default=list),
        ),
    ]
