# Generated by Django 5.0.7 on 2024-08-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_property_string_array_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='image',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
