# Generated by Django 5.0.7 on 2024-08-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_property_photo1_property_photo2_property_photo3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photo1_priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='photo2_priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='photo3_priority',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
